# CONFIG: isMultithreaded = False
# CONFIG: batchSize = 5
# EXPECTED_INPUT_COLUMNS: Farmer #, Farmer Name, Farmer Code, Phone Number, AssignedTo User ID, AssignedTo User Name, Existing Farmer ID, Farmer Status, Farmer Response, Asset Names
"""
QA Data Setup (Master)

Runs existing standalone scripts in sequence to create fresh QA data:
    1. Add Farmer                (or use existing Farmer IDs)
    2. Add Asset                 (N assets per farmer)
    3. Assign & Validate Asset   (creates the CA)
    4. Area Audit V2             (optional, on the new CAs)
    5. Add/Update Crop & DOS     (optional, on the new CAs)

The step scripts are byte-identical copies stored in 'master_components/'.
They are NOT modified; this file only builds each step's input rows and
maps each step's output into the next step's input.

Input rows (one per farmer) are generated by the UI (components/master_flow.js).
Step options come from env_config['masterFlow'].

The UI calls this script in two phases so results appear progressively:
    a) farmers only (steps.farmer=True, asset=False), in small groups
    b) small groups of assets (steps.farmer=False) whose rows carry the farmer
       result from (a) in 'Existing Farmer ID' + 'Farmer Status'/'Farmer Response'
A single call with all steps selected still works end to end.
"""
import os
import importlib.util

# Output rows are per asset, not per input farmer row: tell runner_bridge not to
# merge input rows into results by index.
SKIP_INPUT_MERGE = True

_COMPONENTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'master_components')

STEP_SCRIPTS = {
    'farmer': 'Add_Farmer.py',
    'asset': 'Add_Asset.py',
    'validate': 'Assign_and_Validate_asset_to_Project.py',
    'areaAudit': 'Area_Audit_V2.py',
    'editCa': 'Add_or_update_Crop_and_DOS_to_CA.py',
}

STATUS_COLUMNS = ['Farmer Status', 'Asset Status', 'Validate Status', 'Area Audit Status', 'Crop/DOS Status']

_loaded_modules = {}


def _load_step(step_key):
    """Loads a step script copy as its own module (isolated globals)."""
    if step_key not in _loaded_modules:
        filename = STEP_SCRIPTS[step_key]
        path = os.path.join(_COMPONENTS_DIR, filename)
        spec = importlib.util.spec_from_file_location(f"master_step_{step_key}", path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        _loaded_modules[step_key] = module
    return _loaded_modules[step_key]


def _run_step(step_key, rows, token, env_config):
    """
    Runs one step script on its input rows.
    Returns result rows in the same order. If the script itself crashes,
    every row is marked Fail with the error so later steps skip them.
    """
    if not rows:
        return []
    print(f"\n[MASTER] ===== Step '{step_key}' ({STEP_SCRIPTS[step_key]}) : {len(rows)} row(s) =====", flush=True)
    try:
        results = _load_step(step_key).run(rows, token, env_config)
        if not isinstance(results, list) or len(results) != len(rows):
            raise RuntimeError(f"Unexpected result from {STEP_SCRIPTS[step_key]}: {type(results).__name__}")
        return [r if isinstance(r, dict) else {'Status': 'Fail', 'Response': str(r)} for r in results]
    except Exception as e:
        print(f"[MASTER] Step '{step_key}' crashed: {e}", flush=True)
        return [{**row, 'Status': 'Fail', 'Response': f"{STEP_SCRIPTS[step_key]} error: {e}"} for row in rows]


def _is_pass(result):
    return str((result or {}).get('Status', '')).strip().lower() in ('pass', 'success', 'passed', 'true')


def _message(result):
    result = result or {}
    return str(result.get('Response') or result.get('API_Response') or '').strip()


def _clean_id(value):
    if value is None:
        return None
    text = str(value).strip()
    if not text or text.upper().startswith('NA') or text.lower() in ('none', 'nan'):
        return None
    try:
        return str(int(float(text)))
    except (ValueError, TypeError):
        return text


def _as_number(value):
    """'5982501' -> 5982501 (numeric IDs as an Excel import would give them); other values unchanged."""
    text = str(value).strip() if value is not None else ''
    return int(text) if text.isdigit() else value


def _log_inputs(step_key, rows, columns):
    """Prints the key input values of a step so IDs are visible in the run log."""
    for i, row in enumerate(rows, 1):
        values = ', '.join(f"{c}={row.get(c)!r}" for c in columns)
        print(f"[MASTER] {step_key} input {i}/{len(rows)}: {values}", flush=True)


def run(data, token, env_config):
    flow = (env_config or {}).get('masterFlow') or {}
    steps = flow.get('steps') or {}
    create_farmer = bool(steps.get('farmer'))
    do_asset = bool(steps.get('asset'))
    do_validate = do_asset and bool(steps.get('validate'))
    do_area_audit = do_validate and bool(steps.get('areaAudit'))
    do_edit_ca = do_validate and bool(steps.get('editCa'))

    asset_cfg = flow.get('asset') or {}
    edit_cfg = flow.get('editCa') or {}
    project_id = str(flow.get('projectId') or '').strip()

    # ---------------- STEP 1: FARMERS ----------------
    farmers = []  # one entry per input row
    for plan in data:
        farmers.append({
            'Farmer #': plan.get('Farmer #'),
            'Farmer Name': plan.get('Farmer Name', ''),
            'Farmer Code': plan.get('Farmer Code', ''),
            'Phone Number': plan.get('Phone Number', ''),
            'AssignedTo User ID': plan.get('AssignedTo User ID', ''),
            'User Name': plan.get('AssignedTo User Name', ''),
            'Farmer ID': None,
            'Farmer Status': 'Not Selected',
            'Farmer Response': '',
            'Asset Names': list(plan.get('Asset Names') or []),
        })

    if create_farmer:
        farmer_rows = [{
            'Farmer Name': f['Farmer Name'],
            'Farmer Code': f['Farmer Code'],
            'Phone Number': f['Phone Number'],
            'AssignedTo User ID': f['AssignedTo User ID'],
            'Address': flow.get('farmerAddress', ''),
        } for f in farmers]
        _log_inputs('farmer', farmer_rows, ['Farmer Name', 'Farmer Code', 'Phone Number', 'AssignedTo User ID'])
        for f, res in zip(farmers, _run_step('farmer', farmer_rows, token, env_config)):
            f['Farmer Status'] = 'Pass' if _is_pass(res) else 'Fail'
            f['Farmer Response'] = _message(res)
            f['Farmer ID'] = _clean_id(res.get('Farmer ID')) if _is_pass(res) else None
    else:
        for f, plan in zip(farmers, data):
            f['Farmer ID'] = _clean_id(plan.get('Existing Farmer ID'))
            preset = plan.get('Farmer Status')
            if preset in ('Pass', 'Fail'):
                # Farmer was created in an earlier call of this run (UI runs farmers first, then asset groups)
                f['Farmer Status'] = preset if f['Farmer ID'] or preset == 'Fail' else 'Fail'
                f['Farmer Response'] = plan.get('Farmer Response', '') or ('' if f['Farmer ID'] else 'Farmer ID is missing')
                if f['Farmer Status'] == 'Fail':
                    f['Farmer ID'] = None
            else:
                f['Farmer Status'] = 'Existing' if f['Farmer ID'] else 'Fail'
                f['Farmer Response'] = '' if f['Farmer ID'] else 'Existing Farmer ID is missing'

    # ---------------- STEP 2: ASSETS ----------------
    # records = final output rows (one per asset, or one per farmer when no asset is created)
    records = []
    for f in farmers:
        farmer_ok = f['Farmer ID'] is not None
        asset_names = f['Asset Names'] if do_asset else []
        base = {
            'Farmer #': f['Farmer #'],
            'Farmer Name': f['Farmer Name'],
            'Farmer Code': f['Farmer Code'],
            'Phone Number': f['Phone Number'],
            'AssignedTo User ID': f['AssignedTo User ID'],
            'User Name': f['User Name'],
            'Farmer ID': f['Farmer ID'] or '',
            'Farmer Status': f['Farmer Status'],
            '_messages': [f"Farmer: {f['Farmer Response']}"] if f['Farmer Status'] == 'Fail' and f['Farmer Response'] else [],
        }
        if not asset_names:
            records.append({**base, '_farmer_ok': farmer_ok})
            continue
        for name in asset_names:
            # each asset row gets its own message list (a shared list leaked one asset's errors into all)
            records.append({**base, '_messages': list(base['_messages']), '_farmer_ok': farmer_ok, 'Asset Name': name,
                            'Asset Status': 'Skipped' if do_asset and not farmer_ok else 'Not Selected'})

    if do_asset:
        todo = [r for r in records if r.get('_farmer_ok') and 'Asset Name' in r]
        asset_rows = [{
            'Asset Name': r['Asset Name'],
            'Farmer_ID': _as_number(r['Farmer ID']),
            'Soil Type': asset_cfg.get('soilType', ''),
            'Irrigation Type': asset_cfg.get('irrigationType', ''),
            'Address': asset_cfg.get('address', ''),
            'Declared Area': asset_cfg.get('declaredArea', ''),
        } for r in todo]
        _log_inputs('asset', asset_rows, ['Asset Name', 'Farmer_ID', 'Soil Type', 'Irrigation Type'])
        for r, res in zip(todo, _run_step('asset', asset_rows, token, env_config)):
            ok = _is_pass(res)
            r['Asset Status'] = 'Pass' if ok else 'Fail'
            r['Asset ID'] = _clean_id(res.get('Asset ID')) if ok else ''
            if ok and not r['Asset ID']:
                r['Asset Status'] = 'Fail'
            if r['Asset Status'] == 'Fail':
                r['_messages'].append(f"Asset: {_message(res) or 'Asset ID not returned'}")

    # ---------------- STEP 3: ASSIGN & VALIDATE ----------------
    if do_validate:
        for r in records:
            if 'Asset Name' in r:
                r['Validate Status'] = 'Skipped' if r.get('Asset Status') != 'Pass' else r.get('Validate Status', '')
        todo = [r for r in records if r.get('Asset Status') == 'Pass']
        # IDs as numbers, same as an Excel import gives the standalone script (payload becomes [5982501], not ["5982501"])
        validate_rows = [{'Asset Name': r['Asset Name'], 'Asset ID': _as_number(r['Asset ID']), 'Project ID': _as_number(project_id)} for r in todo]
        _log_inputs('validate', validate_rows, ['Asset Name', 'Asset ID', 'Project ID'])
        for r, res in zip(todo, _run_step('validate', validate_rows, token, env_config)):
            ca_id = _clean_id(res.get('CA ID'))
            ok = _is_pass(res) and ca_id is not None
            r['Validate Status'] = 'Pass' if ok else 'Fail'
            r['CA ID'] = ca_id or ''
            if not ok:
                r['_messages'].append(f"Validate: {_message(res) or 'CA ID not returned'}")

    # ---------------- STEP 4 & 5: AREA AUDIT / EDIT CA (independent of each other) ----------------
    ca_records = [r for r in records if r.get('Validate Status') == 'Pass']

    if do_area_audit:
        for r in records:
            if 'Asset Name' in r and r.get('Validate Status') != 'Pass':
                r['Area Audit Status'] = 'Skipped'
        audit_rows = [{'CAName': r['Asset Name'], 'CA_ID': _as_number(r['CA ID'])} for r in ca_records]
        _log_inputs('areaAudit', audit_rows, ['CAName', 'CA_ID'])
        for r, res in zip(ca_records, _run_step('areaAudit', audit_rows, token, env_config)):
            ok = _is_pass(res)
            r['Area Audit Status'] = 'Pass' if ok else 'Fail'
            r['Audited Area'] = res.get('AuditedArea', '') if ok else ''
            if not ok:
                r['_messages'].append(f"Area Audit: {_message(res)}")

    if do_edit_ca:
        for r in records:
            if 'Asset Name' in r and r.get('Validate Status') != 'Pass':
                r['Crop/DOS Status'] = 'Skipped'
        edit_rows = [{
            'CA Name': r['Asset Name'],
            'CA ID': _as_number(r['CA ID']),
            'Variety Name': edit_cfg.get('varietyName', ''),
            'Date of Sowing (YYYY-MM-DD)': edit_cfg.get('dos', ''),
        } for r in ca_records]
        _log_inputs('editCa', edit_rows, ['CA Name', 'CA ID', 'Variety Name', 'Date of Sowing (YYYY-MM-DD)'])
        for r, res in zip(ca_records, _run_step('editCa', edit_rows, token, env_config)):
            ok = _is_pass(res)
            r['Crop/DOS Status'] = 'Pass' if ok else 'Fail'
            if not ok:
                r['_messages'].append(f"Crop/DOS: {_message(res)}")

    # ---------------- FINAL OUTPUT ----------------
    # One row per created item, laid out as User -> Farmer -> Asset -> CA (name before id), then step statuses.
    output = []
    for r in records:
        selected = [r[c] for c in STATUS_COLUMNS if c in r and r[c] != 'Not Selected']
        all_ok = all(s in ('Pass', 'Existing') for s in selected)
        crop_ok = r.get('Crop/DOS Status') == 'Pass'
        row = {
            'User Name': r.get('User Name', ''),
            'Farmer Name': r.get('Farmer Name', ''),
            'Farmer ID': r.get('Farmer ID', ''),
            'Farmer Code': r.get('Farmer Code', ''),
            'Phone Number': r.get('Phone Number', ''),
            'Asset Name': r.get('Asset Name', ''),
            'Asset ID': r.get('Asset ID', ''),
            'CA ID': r.get('CA ID', ''),
            'Audited Area': r.get('Audited Area', ''),
            'Variety': edit_cfg.get('varietyName', '') if crop_ok else '',
            'DOS': edit_cfg.get('dos', '') if crop_ok else '',
        }
        for c in STATUS_COLUMNS:
            row[c] = r.get(c, 'Not Selected')
        row['Status'] = 'Pass' if all_ok else 'Fail'
        row['Response'] = '; '.join(r['_messages']) if r['_messages'] else ('Success' if all_ok else 'Skipped due to earlier failure')
        output.append(row)
    return output
